### ISSUE TITLE
New release of hdhomerun_record

### ISSUE THREAD

**Issue by averyfreeman** [Yoshiofthewire/docker-hdhomerundvr#3]
Hi!  I just wanted to mention there's a new release of hdhomerun_record

Stable version 20200521:  https://download.silicondust.com/hdhomerun/hdhomerun_record_linux

Beta version 20200701:  https://download.silicondust.com/hdhomerun/hdhomerun_record_linux_beta

I've been using the beta version on Alpine 3.11 for about a month now, seems perfectly stable, although I'm not sure there's any benefit over using the stable channel (they were talking in the forum about improving the dual record server interoperability, etc., doubt that matters to most people)

Have a nice day
Avery

**Comment by Yoshiofthewire** [comment]
Updated to 20200819beta1

**Comment by averyfreeman** [comment]
Nice thank you
